// npm i @apollo/client @apollo/client-integration-tanstack-start graphql rxjs

import type { NewGameRecordDef } from './types';

export const getMockGamesForUser = (userId: string): NewGameRecordDef[] => {
  return [
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Sweet Chili Sauce',
      system: 'Xbox One',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Customizable Name Plate',
      system: 'Nintendo Switch 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Outdoor Portable Fire Pit',
      system: 'Nintendo Gameboy Advance',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Silicone Stretch Lids',
      system: 'Playstation 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Couscous Mix',
      system: 'Playstation 3',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Cinnamon Sugar Donuts',
      system: 'Nintendo Gameboy Advance SP',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Repair Tool Set for Home Improvement',
      system: 'Nintendo Switch 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'White Rice',
      system: 'Nintendo N64',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Adjustable Height Standing Desk Converter',
      system: 'Dreamcast',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Peach Yogurt',
      system: 'Nintendo Wii',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Bamboo Cutting Board',
      system: 'Dreamcast',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Set of Measuring Spoons',
      system: 'Nintendo Gamecube',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Frozen Berry Medley',
      system: 'Gameboy',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Pet Bed',
      system: 'Playstation 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Gluten-Free Biscuits',
      system: 'Xbox One',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Vegan Cheese',
      system: 'Playstation 3',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Wall-Mounted Bookshelf',
      system: 'Nintendo Gameboy Advance',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Biodegradable Trash Bags',
      system: 'Playstation',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Rice Pilaf Mix',
      system: 'Nintendo Gamecube',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Organic Ramen Noodles',
      system: 'Playstation',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Cinnamon Sugar Popcorn',
      system: 'Nintendo Switch',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Garlic Breadsticks',
      system: 'Dreamcast',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Raisin Cinnamon Granola',
      system: 'Nintendo Gameboy Color',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Thai Green Curry Paste',
      system: 'Playstation 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Sriracha Sauce',
      system: 'Nintendo SNES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Hibiscus Herbal Tea',
      system: 'Nintendo Gameboy Advance',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Coconut Almond Granola',
      system: 'Nintendo Switch',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Whole Grain Cereal',
      system: 'Playstation',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Buffalo Chicken Wraps',
      system: 'Playstation 4',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Suction Cup Hooks',
      system: 'Dreamcast',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Vegetable Lentil Soup',
      system: 'Dreamcast',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Paint By Numbers Kit',
      system: 'Xbox 360',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Coconut Chips',
      system: 'Xbox Series X',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Pressure Cooker',
      system: 'Nintendo Gameboy Advance SP',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Coconut Oil Spray',
      system: 'Xbox One',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Caramel Apple Taffy',
      system: 'Xbox 360',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Herb Drying Rack',
      system: 'Nintendo SNES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Vegetable Potstickers',
      system: 'Nintendo DS',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Smart LED Desk Lamp',
      system: 'Playstation 3',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'DIY Lip Balm Making Kit',
      system: 'Nintendo Wii U',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'LED Flashing Pet Collar',
      system: 'Xbox One',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Heat-Resistant Silicone Mat',
      system: 'Gameboy',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Two-Tone Windbreaker',
      system: 'Nintendo SNES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Peach Fruit Cups',
      system: 'Playstation 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Beef Stroganoff Mix',
      system: 'Nintendo Gameboy Color',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Butternut Squash Soup',
      system: 'Nintendo Gamecube',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Portable Pet Stroller',
      system: 'Playstation 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Personal Blender with Cups',
      system: 'Nintendo Wii U',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Travel Shoe Bags Set',
      system: 'Xbox Series X',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Magnetic Curtain Tiebacks',
      system: 'Nintendo Switch 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Garlic Parmesan Roasted Potatoes',
      system: 'Nintendo Gamecube',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Smart Water Bottle',
      system: 'Playstation 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Garlic Butter Shrimp',
      system: 'Nintendo DS',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Garam Masala Spice Blend',
      system: 'Nintendo Switch',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Interactive Plush Toy',
      system: 'Nintendo NES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Electric Screwdriver',
      system: 'Nintendo NES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Almond Joy Snack Bars',
      system: 'Nintendo SNES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Whole Wheat Pita Bread',
      system: 'Nintendo Gamecube',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Portable UV Sterilizer',
      system: 'Nintendo Wii U',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Ceramic Knife Set',
      system: 'Nintendo DS',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Sweet Potato Noodles',
      system: 'Nintendo SNES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Fitness Foam Roller',
      system: 'Playstation 4',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'LED Flashing Pet Collar',
      system: 'Nintendo Switch',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: "Children's Science Experiment Lab Kit",
      system: 'Nintendo SNES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Tomatillo Salsa',
      system: 'Nintendo NES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Coffee Grinder',
      system: 'Nintendo NES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Jalapeño Cornbread',
      system: 'Nintendo Switch',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Repair Tool Set for Home Improvement',
      system: 'Nintendo NES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Coffee Making Kit',
      system: 'Playstation 5',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Snap-On Tupperware Set',
      system: 'Nintendo N64',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Honey mustard chicken tenders',
      system: 'Nintendo Gameboy Advance SP',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Pita Bread',
      system: 'Gameboy',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Nordic Berry Smoothie',
      system: 'Xbox',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Luxury Bath Robe',
      system: 'Nintendo SNES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Weighted Blanket',
      system: 'Nintendo Switch',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: "Kids' Crafting Station",
      system: 'Playstation 3',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Spiralizer',
      system: 'Xbox One',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Beef Enchilada Casserole',
      system: 'Playstation 3',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Field Journal',
      system: 'Playstation 3',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Mashed Sweet Potatoes',
      system: 'Xbox One',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'LED Desk Lamp with USB Charging Port',
      system: 'Playstation',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Portable Campfire',
      system: 'Playstation 5',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Carrot and Celery Sticks',
      system: 'Nintendo DS',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Peach Yogurt',
      system: 'Playstation 4',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Handheld Shower Head',
      system: 'Playstation 4',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Scent Diffuser',
      system: 'Nintendo SNES',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Tomatillo Salsa',
      system: 'Playstation 4',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Maple Pecan Granola',
      system: 'Playstation',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Rechargeable Hand Warmer',
      system: 'Xbox',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Cordless Water Flosser',
      system: 'Nintendo N64',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Habanero Hot Sauce',
      system: 'Playstation 5',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Garden Vegetable Soup',
      system: 'Nintendo Gameboy Advance',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Coconut Milk Yogurt',
      system: 'Playstation 4',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Heavy-Duty Utility Tote',
      system: 'Playstation 2',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Cat Scratching Post with Toys',
      system: 'Nintendo Wii',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Baking Powder',
      system: 'Xbox One',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Peach Yogurt',
      system: 'Playstation',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Artisan Pickles',
      system: 'Nintendo Gameboy Advance',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: true,
      name: 'Fruit Medley Juice',
      system: 'Playstation 5',
      userId,
    },
    {
      editionDetails: null,
      isSpecialEdition: false,
      name: 'Roasted Red Pepper Dip',
      system: 'Xbox Series X',
      userId,
    },
  ];
};
