/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIndexRouteImport } from './routes/collection/index'
import { Route as ApiGamesIndexRouteImport } from './routes/api/games/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGamesIdIndexRouteImport } from './routes/api/games/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesIndexRoute = ApiGamesIndexRouteImport.update({
  id: '/api/games/',
  path: '/api/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesIdIndexRoute = ApiGamesIdIndexRouteImport.update({
  id: '/api/games/$id/',
  path: '/api/games/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection/': typeof CollectionIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/api/games/$id/': typeof ApiGamesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/games': typeof ApiGamesIndexRoute
  '/api/games/$id': typeof ApiGamesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection/': typeof CollectionIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/api/games/$id/': typeof ApiGamesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection/'
    | '/api/auth/$'
    | '/api/games/'
    | '/api/games/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/api/auth/$' | '/api/games' | '/api/games/$id'
  id:
    | '__root__'
    | '/'
    | '/collection/'
    | '/api/auth/$'
    | '/api/games/'
    | '/api/games/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGamesIndexRoute: typeof ApiGamesIndexRoute
  ApiGamesIdIndexRoute: typeof ApiGamesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/': {
      id: '/api/games/'
      path: '/api/games'
      fullPath: '/api/games/'
      preLoaderRoute: typeof ApiGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$id/': {
      id: '/api/games/$id/'
      path: '/api/games/$id'
      fullPath: '/api/games/$id/'
      preLoaderRoute: typeof ApiGamesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGamesIndexRoute: ApiGamesIndexRoute,
  ApiGamesIdIndexRoute: ApiGamesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
