/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RouteTreeGenRouteImport } from './routes/routeTree.gen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteTreeGenRoute = RouteTreeGenRouteImport.update({
  id: '/routeTree/gen',
  path: '/routeTree/gen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/routeTree/gen': typeof RouteTreeGenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/routeTree/gen': typeof RouteTreeGenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/routeTree/gen': typeof RouteTreeGenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/routeTree/gen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/routeTree/gen'
  id: '__root__' | '/' | '/routeTree/gen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RouteTreeGenRoute: typeof RouteTreeGenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routeTree/gen': {
      id: '/routeTree/gen'
      path: '/routeTree/gen'
      fullPath: '/routeTree/gen'
      preLoaderRoute: typeof RouteTreeGenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RouteTreeGenRoute: RouteTreeGenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
